CREATE TABLE users (
    sno INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    name TEXT,
    email TEXT UNIQUE NOT NULL,
    phoneno TEXT,
    password TEXT NOT NULL,
    status INTEGER DEFAULT 1 NOT NULL,
    role TEXT DEFAULT 'user' NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
);